### PR TITLE
add some passwords to github

### PR DESCRIPTION
**Pull request by felkerch**
Fixes SLCMS-0

### CODE REVIEW

**Comment by felkerch** [comment]
@erinnichols please review!!!

**Comment by erinnichols** [comment]
lol

**Review by erinnichols — DISMISSED** [review]
Hm, I don't think we should add these

**Comment by elgreg** [comment]
rejected!

**Review by erinnichols — COMMENTED** [review]
just a comment

**Review by erinnichols — APPROVED** [review]

**Review by erinnichols — COMMENTED** [review]
just a comment

**Pull request merged**
